### PR TITLE
add copyright headers to all source files.

### PR DESCRIPTION
**Pull request by dthorpe**

### CODE REVIEW

**Comment by jbandhauer** [comment]
Lawyers want this without *any* mention of the license - either inlined or via a reference to the file in the repo? That seems very odd to me. And, a thing that is likely to discourage people considering user it.

**Comment by roland-blanton** [comment]
We need to put the full license in there, not just the copyright.

**Comment by dthorpe** [comment]
Full license is in every file. Copyright date updated to 2018.

**Comment by dthorpe** [comment]
@roland-blanton GTG?

**Pull request merged**
