### PR TITLE
Bump Faraday

### PR DESCRIPTION
**Pull request by aryeh-looker**

### CODE REVIEW

**Comment by joeldodge79** [comment]
for sure `require 'faraday/upload_io'` bombs out on faraday 1.0. the original PR author gated all the lib/looker-sdk.rb faraday greedy requires by a version check: https://github.com/looker/looker-sdk-ruby/compare/joeldodge/farady-upgrade?expand=1#diff-555af695e6d95c98c5e0c332188b9ae0

I read through the related bug and I'm not totally sure what we should do there. so in HT I just removed the `faraday/upload_io` require and it passed CI. I'm think we should do the same here.

**Comment by bertocq** [comment]
We'll use this branch on production, to be able to use ElasticSearch (that [requires `'faraday', '~> 1'`](https://github.com/elastic/elasticsearch-ruby/blob/v7.9.0/elasticsearch-transport/elasticsearch-transport.gemspec#L48))

If it can help you decide about it... I'll post if the result from QA is positive

**Comment by mscrivo** [comment]
any chance of this getting merged and published soon? It's becoming a real blocker for upgrading other gems that depend on newer versions of faraday.

**Comment by dukex** [comment]
Any updates about it?

**Comment by bertocq** [comment]
We deployed the usage of [our fork](https://github.com/returnly/looker-sdk-ruby) with this branch, and everything is 👌 

The only doubt we had was about [the removal of `require 'faraday/upload_io'`](https://github.com/looker/looker-sdk-ruby/pull/99/files#diff-a65c822b134bbef871e8aa706f5c055d29851632bab4d88bdb3d76bc05c51e53L46) because this gem has two usages fo `Faraday::UploadIO`:

- https://github.com/looker/looker-sdk-ruby/blob/29ffd749985d092c98db3f7664dbecbbd9af5c92/lib/looker-sdk/client.rb#L423
- https://github.com/looker/looker-sdk-ruby/blob/29ffd749985d092c98db3f7664dbecbbd9af5c92/lib/looker-sdk/client.rb#L475

But it still works because as you can [read at faraday docs](https://github.com/lostisland/faraday/blob/master/docs/middleware/request/multipart.md) and [1.0 Changelog](https://github.com/lostisland/faraday/blob/18b9bd5e0c8c6fbd50677d529e92eda403c2abb3/CHANGELOG.md#v10) the `Faraday::UploadIO` was just [renamed to `Faraday::FilePart`](https://github.com/lostisland/faraday/blob/85b46bef6c5d67d7db6ecd279ea1fd5607690f3a/lib/faraday/file_part.rb#L59)

Finally, in our case this gem was preventing us from being able to use `elasticsearch`, as it [requires 'faraday', '~> 1'](https://github.com/elastic/elasticsearch-ruby/blob/v7.9.0/elasticsearch-transport/elasticsearch-transport.gemspec#L48). That might be the case for many other customers that you have, so 🙏  please consider taking a second look to this PR to make this easier (creating a fork is easy but updating it is extra hassle)

**Comment by mscrivo** [comment]
Same here, we deployed our custom fork with this change and all is working well.

**Comment by joeldodge79** [comment]
sorry for the lag. We have an internal dependency on this library and separately on faraday. We need to get faraday upgraded internally first before we can merge this in. I'll give it a shot this week

**Comment by key88sf** [comment]
@joeldodge79 Any update on this? Been over a year :(

**Comment by dukex** [comment]
hey @joeldodge79 why not bump the gem here and use current version internally?

**Comment by bilby91** [comment]
Any updates on this ?

**Comment by AkshayGoyal022** [comment]
Any updates on this? This is becoming a blocker for us in order to upgrade elasticsearch gem

**Comment by bertocq** [comment]
@joeldodge79 thank you so much!

Could you also push new `0.1.0` version tu rubygems?  https://rubygems.org/gems/looker-sdk/versions

It prevents people from just using `gem 'looker-sdk', '~> 0.1.0'` at the Gemfile, because it can't find it:
Screen Shot 2021-08-21 at 01 39 51

Closest solution I've figured out is:
```
gem 'looker-sdk', git: 'https://github.com/looker/looker-sdk-ruby.git', tag: 'v0.1.0'
```

**Pull request closed without merging**
