### PR TITLE
Formalize gem spec content for official gem publication

### PR DESCRIPTION
**Pull request by dthorpe**
Tighten up rake test:all

### CODE REVIEW

**Comment by jgn** [comment]
:1st_place_medal:

**Comment by the-michael-toy** [comment]
Looks reasonable to me. 🐑 🇮🇹

**Comment by dthorpe** [comment]
Fixes #48 
Fixes #52

**Comment by dthorpe** [comment]
Fixes #48

**Comment by jbandhauer** [comment]
🎉 Thanks @dthorpe !

**Pull request merged**
